### ISSUE TITLE
Develop the Indexer for PeARSearch

### ISSUE THREAD

**Issue by nandajavarma** [PeARSearch/PeARS#25]
The development of the network depends on this, since the DHT should know how/where the indexer is going to store the peer profile, url dists, wordclouds, etc. So we have to kick start the development of this part soon.

**Comment by nandajavarma** [comment]
The way I imagine the indexer to store the data as of now is as follows:
The peer profile will be a column in a database table say, settings. Other columns in this table will be items like name of the pear, if the pear would like to anonymous, etc. @stultus was saying he will think of a better way to do this. The issue with this is that there will only be a single entry corresponding to that pear in this table. So for just a single entry should we go for a database table? It would still be efficient that reading from files. Also, it would be so easy for the API to fetch these data from a pear. But, Is there a better way?
The url dists and wordclouds will have separate database tables which will be populated and updated by the indexer. Like mentioned before, this makes it easier for the network API to fetch data.

**Comment by minimalparts** [comment]
Couldn't agree more. We need the indexer now. So... let's take stock of what we have...

1) the browsing-history-analyser repo has a dirty version of the indexer using the user's browsing history. Ideally, we would like to index pages as they are visited, using the Firefox plugin @sepulchered is building (we'd also talked about a daemon at some point, and @bsbarkur was looking into this -- see discussion at http://lists.pearsearch.org/t/browsing-history-analyser/33/9). But the core code (i.e. taking the text of the document and transforming it into a vector + building the profile vector) is there.

2) @nandajavarma, could you say a bit more about how the system is to access the different user profiles, built on different pears? I'm not clear on this.

3) As for putting the document vectors in a database, we have create_openvectors_db.py in the PeARS repo, which just needs two tweaks to similarly produce the document vectors database from the locally indexed stuff. If I understand it right, url/page title/word clouds would be added to the same database under different tables, correct?

4) I'm out of everything until 14th September (deadline for grant application) but I could give this a go afterwards, if no one took care of it in the meantime. I don't think it would take long. 

What do you all say?

**Comment by nandajavarma** [comment]
Hey @minimalparts ,
So to access the user profile, there will be an API written as part of each of the pear client code. So when the DHT returns the list of the best pears the local pear client will send a GET API request to each of the pear in the pear list, asking for the pear profile, urls_dists, and wordclouds. On receiving this request, each pear fetches data from the corresponding databases and send it as a response to the API call. Does that make sense? I will write the code for adding the databases and for the API, so you will get a better idea of the process.
It is quite straightforward since you have already done the heavy lifting. ;-) Let me hack on your code and try to make it work from command line. Integrating with the firefox-plugin/daemon can be thought of later, I guess.

**Comment by minimalparts** [comment]
Hey @nandajavarma,
ok, thanks! And how does the DHT collect the pear profiles in the first place? (I.e. prior to any call to best_pears.py or whatever?)
Would be fantastic if you could hack something away. Thanks!!

**Comment by nandajavarma** [comment]
@minimalparts DHT will not make use of the name, bio, and such details of the pear. Just that numpy array. The pear in which the query takes place tries to fetch these data from the best pear. If the best pear has chosen to stay anonymous it won't get any response.

**Comment by minimalparts** [comment]
@nandajavarma right, right. Sorry, I again misphrased my question... I meant, we need a piece of code that collects the pears' numpy arrays as they join the network, and update everybody, right?

**Comment by nandajavarma** [comment]
@minimalparts That'll be a part of the DHT code in the local of each pear

**Comment by minimalparts** [comment]
@nandajavarma cool. I look forward to the code :) :) :)

**Comment by minimalparts** [comment]
I am closing this because we now have the indexer integrated.
