### ISSUE TITLE
Design doc for PeARS DHT

### ISSUE THREAD

**Issue by nandajavarma** [PeARSearch/PeARS#9]
The DHT design doc for PeARS is under progress over here: https://docs.google.com/document/d/12Gqt6oPpNn-3wXQNVORXNv7jKQcgk81hARhgDoIjWUw/edit?usp=sharing

Due to last week at work and other wrapping up stuff hurries, I couldn't work on this the way I intended to. Adding an issue for this to speed myself up.

**Comment by minimalparts** [comment]
I am closing this, since we now have the DHT. We should open a separate issue about all the documentation needed, given the current state of the project.
